var lunches = [
    "El Mexsal",
    "Two Jacks",
    "Red Robin",
    "Panda Express",
    "Taco Bell",
    "India Palace",
    "Raising Cane's",
    "Chick-Fil-A",
    "Thai Neighbor",
    "Wingers",
    "La Casita",
    "El Gallo Giro",
    "Gandolfo's",
    "Joe Bandido's",
    "Subway",
    "Betos",
    "Sushi Ya",
    "Saigon",
    "Burger Supreme",
    "Cremery",
]
